/**
 * Tool Registry - All generated MCP tools
 * DO NOT EDIT - This file is auto-generated by scripts/generate.ts
 */

import type { ParsedOperation } from "../generator/openapi-parser.js";

import { admin_console_and_uiTools } from "./generated/admin_console_and_ui/index.js";
import { ai_servicesTools } from "./generated/ai_services/index.js";
import { apiTools } from "./generated/api/index.js";
import { authenticationTools } from "./generated/authentication/index.js";
import { bigipTools } from "./generated/bigip/index.js";
import { billing_and_usageTools } from "./generated/billing_and_usage/index.js";
import { blindfoldTools } from "./generated/blindfold/index.js";
import { bot_and_threat_defenseTools } from "./generated/bot_and_threat_defense/index.js";
import { cdnTools } from "./generated/cdn/index.js";
import { ce_managementTools } from "./generated/ce_management/index.js";
import { certificatesTools } from "./generated/certificates/index.js";
import { cloud_infrastructureTools } from "./generated/cloud_infrastructure/index.js";
import { container_servicesTools } from "./generated/container_services/index.js";
import { data_and_privacy_securityTools } from "./generated/data_and_privacy_security/index.js";
import { data_intelligenceTools } from "./generated/data_intelligence/index.js";
import { ddosTools } from "./generated/ddos/index.js";
import { dnsTools } from "./generated/dns/index.js";
import { managed_kubernetesTools } from "./generated/managed_kubernetes/index.js";
import { marketplaceTools } from "./generated/marketplace/index.js";
import { networkTools } from "./generated/network/index.js";
import { network_securityTools } from "./generated/network_security/index.js";
import { nginx_oneTools } from "./generated/nginx_one/index.js";
import { object_storageTools } from "./generated/object_storage/index.js";
import { observabilityTools } from "./generated/observability/index.js";
import { rate_limitingTools } from "./generated/rate_limiting/index.js";
import { secops_and_incident_responseTools } from "./generated/secops_and_incident_response/index.js";
import { service_meshTools } from "./generated/service_mesh/index.js";
import { shapeTools } from "./generated/shape/index.js";
import { sitesTools } from "./generated/sites/index.js";
import { statisticsTools } from "./generated/statistics/index.js";
import { supportTools } from "./generated/support/index.js";
import { telemetry_and_insightsTools } from "./generated/telemetry_and_insights/index.js";
import { tenant_and_identityTools } from "./generated/tenant_and_identity/index.js";
import { threat_campaignTools } from "./generated/threat_campaign/index.js";
import { usersTools } from "./generated/users/index.js";
import { virtualTools } from "./generated/virtual/index.js";
import { vpm_and_node_managementTools } from "./generated/vpm_and_node_management/index.js";
import { wafTools } from "./generated/waf/index.js";

/**
 * All registered tools from all domains
 */
export const allTools: ParsedOperation[] = [
  ...admin_console_and_uiTools,
  ...ai_servicesTools,
  ...apiTools,
  ...authenticationTools,
  ...bigipTools,
  ...billing_and_usageTools,
  ...blindfoldTools,
  ...bot_and_threat_defenseTools,
  ...cdnTools,
  ...ce_managementTools,
  ...certificatesTools,
  ...cloud_infrastructureTools,
  ...container_servicesTools,
  ...data_and_privacy_securityTools,
  ...data_intelligenceTools,
  ...ddosTools,
  ...dnsTools,
  ...managed_kubernetesTools,
  ...marketplaceTools,
  ...networkTools,
  ...network_securityTools,
  ...nginx_oneTools,
  ...object_storageTools,
  ...observabilityTools,
  ...rate_limitingTools,
  ...secops_and_incident_responseTools,
  ...service_meshTools,
  ...shapeTools,
  ...sitesTools,
  ...statisticsTools,
  ...supportTools,
  ...telemetry_and_insightsTools,
  ...tenant_and_identityTools,
  ...threat_campaignTools,
  ...usersTools,
  ...virtualTools,
  ...vpm_and_node_managementTools,
  ...wafTools,
];

/**
 * Get tools by domain
 */
export function getToolsByDomain(domain: string): ParsedOperation[] {
  return allTools.filter((tool) => tool.domain === domain);
}

/**
 * Get tool by name
 */
export function getToolByName(name: string): ParsedOperation | undefined {
  return allTools.find((tool) => tool.toolName === name);
}

/**
 * Get all domain names
 */
export function getAllDomains(): string[] {
  return [...new Set(allTools.map((tool) => tool.domain))];
}

/**
 * Get tool count by domain
 */
export function getToolCountByDomain(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const tool of allTools) {
    counts[tool.domain] = (counts[tool.domain] ?? 0) + 1;
  }
  return counts;
}

export default allTools;
